version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  app: &app
    build:
      context: .
      dockerfile: ./compose/local/go/Dockerfile
      target: dev
    image: local_app
    depends_on:
      - postgres
    ports:
      - "8000:8000"
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.envs/.local/.postgres
      - ./.envs/.local/.openai
      - ./.envs/.local/.app

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:5.0.5-alpine
    ports:
      - "6379:6379"
